
(in-package :shop2-user)
(defproblem case4 atHome
(	(on(obj1 table))
	(on(obj2 table))
	(on(obj3 table))
	(on(obj4 table))
	(on(obj5 table))
	(at somewhereInRoom)
	(has(cupboard shelf1))
	(has(cupboard shelf2))
	(category shelf1 1)
	(category shelf2 2)
	(close cupboard)
	(isTable table)
	(isCupboard cupboard)
	(category obj1 1)
	(category obj2 2)
	(category obj3 2)
	(category obj4 2)
	(category obj5 1)
	(objectShouldBeMoved obj3)
	(objectShouldBeMoved obj1)
	(categoryShouldBeMoved 1)
	) ((start  table cupboard)))

(find-plans 'case4 :verbose :plans :which :FIRST)
